on:
  push
permissions:
  contents: write
  
env:
  LIBRARY_VERSION_NUMBER: 0.2.${{ github.run_number }}
  
jobs:
  package-libre-office:
    runs-on: ubuntu-latest
    name: Package LibreOffice extension
    steps:
    - uses: actions/checkout@v3
    - name: Package extension
      run: |
        mkdir packages/libreoffice/dictionaries
        cp hunspell/* ${GITHUB_WORKSPACE}/packages/libreoffice/dictionaries/
        sed -i 's/LIBRARY_VERSION/${{ env.LIBRARY_VERSION_NUMBER }}/g' ${GITHUB_WORKSPACE}/packages/libreoffice/description.xml
        cd ${GITHUB_WORKSPACE}/packages/libreoffice/
        zip ${GITHUB_WORKSPACE}/packages/libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.zip * -r
        mv -v ${GITHUB_WORKSPACE}/packages/libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.zip ${GITHUB_WORKSPACE}/packages/libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.oxt

    - name: Upload extension as artifact
      uses: actions/upload-artifact@v3
      with:
        name: libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}
        path: packages/libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.oxt
        if-no-files-found: error

        
  package-mozilla:
    runs-on: ubuntu-latest
    name: Package mozilla extension
    steps:
    - uses: actions/checkout@v3
    - name: Package extension
      run: |
        mkdir packages/mozilla/dictionaries
        cp hunspell/* ${GITHUB_WORKSPACE}/packages/mozilla/dictionaries/
        sed -i 's/LIBRARY_VERSION/${{ env.LIBRARY_VERSION_NUMBER }}/g' ${GITHUB_WORKSPACE}/packages/mozilla/manifest.json
        cd ${GITHUB_WORKSPACE}/packages/mozilla/
        zip ${GITHUB_WORKSPACE}/packages/mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.zip * -r
        mv -v ${GITHUB_WORKSPACE}/packages/mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.zip ${GITHUB_WORKSPACE}/packages/mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.xpi

    - name: Upload extension as artifact
      uses: actions/upload-artifact@v3
      with:
        name: mozilla-${{ env.LIBRARY_VERSION_NUMBER }}
        path: packages/mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.xpi
        if-no-files-found: error
  
  release:
    runs-on: ubuntu-latest
    needs: [package-libre-office, package-mozilla]
    steps:
      
    - uses: actions/download-artifact@v2
      with:
        name: libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}
        path: packages/
    
    - uses: actions/download-artifact@v2
      with:
        name: mozilla-${{ env.LIBRARY_VERSION_NUMBER }}
        path: packages/
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.LIBRARY_VERSION_NUMBER }}
        release_name: ${{ env.LIBRARY_VERSION_NUMBER }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: packages/libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.oxt
        asset_name: libreoffice-${{ env.LIBRARY_VERSION_NUMBER }}.oxt
        asset_content_type: application/zip

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: packages/mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.xpi
        asset_name: mozilla-${{ env.LIBRARY_VERSION_NUMBER }}.xpi
        asset_content_type: application/zip